# Source: cluster-api-byoh/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: fc2659e4-0300-4b29-bc42-149dbc4472ce
  namespace: fc2659e4
spec:
  clusterNetwork:
    pods:
      cidrBlocks: [10.233.64.0/18]
    serviceDomain: cluster.local
    services:
      cidrBlocks: [10.233.0.0/18]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: fc2659e4-0300-4b29-bc42-149dbc4472ce-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: ByoCluster
    name: fc2659e4-0300-4b29-bc42-149dbc4472ce
